# Generated by Django 5.0.1 on 2025-11-03 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('role', models.TextField(default='You are a helpful AI assistant for a beauty salon. You help with scheduling appointments, answering questions, and providing information.')),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for the AI')),
                ('context', models.TextField(blank=True, help_text='Business context, services, pricing, etc.')),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=500)),
                ('model', models.CharField(default='gpt-4-turbo-preview', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'db_table': 'prompts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('source', models.CharField(choices=[('web', 'Web Interface'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('api', 'API')], default='web', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message_count', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user_id', '-updated_at'], name='conversatio_user_id_e93dff_idx'), models.Index(fields=['source', 'external_id'], name='conversatio_source_7fe73f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('photo_id', models.IntegerField(blank=True, null=True)),
                ('context_used', models.JSONField(blank=True, default=list)),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx')],
            },
        ),
    ]
