# Generated by Django 5.0.1 on 2025-11-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_freemium_plan'),
        ('subscriptions', '0002_update_plans'),
    ]

    operations = [
    ]
