# Generated by Django 5.0.1 on 2025-11-03 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('integration_type', models.CharField(choices=[('telegram', 'Telegram Bot'), ('whatsapp', 'WhatsApp Business'), ('google_calendar', 'Google Calendar')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Setup'), ('active', 'Active'), ('error', 'Error'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('messages_received', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'db_table': 'integrations',
                'ordering': ['-created_at'],
                'unique_together': {('user_id', 'integration_type')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['integration', '-created_at'], name='webhook_eve_integra_87eda6_idx'), models.Index(fields=['is_processed'], name='webhook_eve_is_proc_3846b5_idx')],
            },
        ),
    ]
