# Generated by Django 5.0.1 on 2025-11-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VectorStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('embedding_model', models.CharField(default='text-embedding-ada-002', max_length=100)),
                ('chunk_size', models.IntegerField(default=1000)),
                ('chunk_overlap', models.IntegerField(default=200)),
                ('total_embeddings', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vector Store',
                'verbose_name_plural': 'Vector Stores',
                'db_table': 'vector_stores',
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('document', 'Document'), ('photo', 'Photo'), ('message', 'Message'), ('prompt', 'Prompt')], db_index=True, max_length=20)),
                ('source_id', models.IntegerField(db_index=True)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Embedding',
                'verbose_name_plural': 'Embeddings',
                'db_table': 'embeddings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='embeddings_source__716927_idx')],
            },
        ),
    ]
