# Generated by hand to add pgvector column and index
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('embeddings', '0001_initial'),
    ]

    operations = [
        # Add pgvector column to embeddings table (dimension 1536 for ada-002)
        migrations.RunSQL(
            sql="""
            ALTER TABLE embeddings
            ADD COLUMN IF NOT EXISTS vector vector(1536);
            """,
            reverse_sql="""
            ALTER TABLE embeddings
            DROP COLUMN IF EXISTS vector;
            """
        ),
        # Optional performance index for cosine similarity with ivfflat
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Create index only if extension/operator class available
                -- and index does not already exist
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_class c
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE c.relname = 'idx_embeddings_vector'
                      AND n.nspname = current_schema()
                ) THEN
                    CREATE INDEX idx_embeddings_vector
                    ON embeddings
                    USING ivfflat (vector vector_cosine_ops)
                    WITH (lists = 100);
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_embeddings_vector;
            """
        ),
    ]


